version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: city-wandr:prod
    container_name: city-wandr
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - web

networks:
  web:
    driver: bridge 